spring:
  datasource:
    username: utbzwohtpzyweb
    password: a0ce77ac36dc6524a2ef99353ca9aa95682cbae5677cae7dc117614ed0707062
    url: jdbc:postgresql://ec2-54-225-72-238.compute-1.amazonaws.com:5432/dc7cc6cqo9sod4
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/movie
  port: 8085