spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:~/test
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

server:
  servlet:
    context-path: /service/reservation
  port: 8083