spring:
  datasource:
    username: {USERNAME}
    password: {PASSWORD}
    url: jdbc:postgresql://{HOST}:5432/{DATABASE}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update