spring:
  datasource:
    username: vujhhnaszgbkzx
    password: 19f9296d5c81f20ba93209c53b7a901fde9ee39896f1e5e0e18d2c0ea01111b1
    url: jdbc:postgresql://ec2-23-21-148-223.compute-1.amazonaws.com:5432/deqem0e9g3bqjc
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/show
  port: 8084